/**
 * Parse CSV content to JSON
 * Simple CSV parser without external dependencies
 */
function parseCSV(csvContent) {
  const lines = csvContent.split('\n').filter(line => line.trim());
  
  if (lines.length < 2) {
    throw new Error('CSV file must contain headers and at least one data row');
  }

  // Parse headers
  const headers = lines[0].split(',').map(h => h.trim().replace(/['"]/g, ''));
  
  // Parse data rows
  const books = [];
  for (let i = 1; i < lines.length; i++) {
    const values = parseCSVLine(lines[i]);
    
    if (values.length !== headers.length) {
      console.warn(`Row ${i + 1} has ${values.length} columns, expected ${headers.length}. Skipping.`);
      continue;
    }

    const book = {};
    headers.forEach((header, index) => {
      book[header] = values[index];
    });
    
    books.push(book);
  }

  return books;
}

/**
 * Parse a single CSV line handling quoted values
 */
function parseCSVLine(line) {
  const values = [];
  let current = '';
  let inQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    
    if (char === '"') {
      inQuotes = !inQuotes;
    } else if (char === ',' && !inQuotes) {
      values.push(current.trim());
      current = '';
    } else {
      current += char;
    }
  }
  
  values.push(current.trim());
  return values;
}

/**
 * Validate and transform book data from CSV
 */
function validateBookData(bookData) {
  const errors = [];
  const book = {};

  // Required fields
  if (!bookData.title || bookData.title.trim() === '') {
    errors.push('Title is required');
  } else {
    book.title = bookData.title.trim();
  }

  if (!bookData.author || bookData.author.trim() === '') {
    errors.push('Author is required');
  } else {
    book.author = bookData.author.trim();
  }

  if (!bookData.aboutBook || bookData.aboutBook.trim() === '') {
    // aboutBook is optional - will be generated by Gemini AI
    book.aboutBook = `${bookData.title} by ${bookData.author}`;
  } else {
    book.aboutBook = bookData.aboutBook.trim();
    book.description = bookData.aboutBook.trim(); // Backward compatibility
  }

  if (!bookData.categories || bookData.categories.trim() === '') {
    errors.push('Categories is required');
  } else {
    book.categories = bookData.categories.trim();
  }

  if (!bookData.price || isNaN(parseFloat(bookData.price))) {
    errors.push('Valid price is required');
  } else {
    book.price = parseFloat(bookData.price);
  }

  if (!bookData.pages || isNaN(parseInt(bookData.pages))) {
    errors.push('Valid pages count is required');
  } else {
    book.pages = parseInt(bookData.pages);
  }

  if (!bookData.coverImage || bookData.coverImage.trim() === '') {
    errors.push('Cover image URL is required');
  } else {
    book.coverImage = bookData.coverImage.trim();
  }

  // Optional fields
  book.aboutAuthor = bookData.aboutAuthor?.trim() || undefined;
  book.isbn = bookData.isbn?.trim() || undefined;
  book.publisher = bookData.publisher?.trim() || undefined;
  book.language = bookData.language?.trim() || 'English';
  book.format = bookData.format?.trim() || 'Paperback';
  
  // Map ageGroup to valid enum values
  if (bookData.ageGroup) {
    const ageGroupMap = {
      'Children': 'Children',
      'Young Adult': 'Young Adult',
      'Adult': 'Adult',
      'All Ages': 'All Ages',
      // Common variations
      '16+': 'Adult',
      '18+': 'Adult',
      'All': 'All Ages',
      'Kids': 'Children',
      'Teen': 'Young Adult',
      'Teenager': 'Young Adult',
      'YA': 'Young Adult'
    };
    
    const mappedAgeGroup = ageGroupMap[bookData.ageGroup.trim()];
    book.ageGroup = mappedAgeGroup || undefined;
    
    if (bookData.ageGroup.trim() && !mappedAgeGroup) {
      errors.push(`Invalid ageGroup "${bookData.ageGroup}". Use: Children, Young Adult, Adult, All Ages, 16+, or All`);
    }
  } else {
    book.ageGroup = undefined;
  }
  
  book.publishedDate = bookData.publishedDate || undefined;
  
  book.originalPrice = bookData.originalPrice ? parseFloat(bookData.originalPrice) : undefined;
  book.stock = bookData.stock ? parseInt(bookData.stock) : 0;
  
  // Boolean fields
  book.featured = bookData.featured === 'true' || bookData.featured === '1';
  book.bestseller = bookData.bestseller === 'true' || bookData.bestseller === '1';
  book.newArrival = bookData.newArrival === 'true' || bookData.newArrival === '1';

  return { book, errors };
}

module.exports = {
  parseCSV,
  validateBookData
};
